<?php

return [
    'GB' => [
        'name' => 'United Kingdom',
        'currency' => 'GBP',
        'currency_symbol' => '£',
        'locale' => 'en_GB',
        'language' => 'en',
        'timezone' => 'Europe/London',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$',
        'portals' => ['rightmove', 'zoopla', 'onthemarket'],
    ],
    'IE' => [
        'name' => 'Ireland',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'locale' => 'en_IE',
        'language' => 'en',
        'timezone' => 'Europe/Dublin',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^[A-Z0-9]{3} ?[A-Z0-9]{4}$',
        'portals' => [],
    ],
    'AU' => [
        'name' => 'Australia',
        'currency' => 'AUD',
        'currency_symbol' => '$',
        'locale' => 'en_AU',
        'language' => 'en',
        'timezone' => 'Australia/Sydney',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'portals' => ['domain', 'realestate_com_au'],
    ],
    'CA' => [
        'name' => 'Canada',
        'currency' => 'CAD',
        'currency_symbol' => '$',
        'locale' => 'en_CA',
        'language' => 'en',
        'timezone' => 'America/Toronto',
        'date_format' => 'Y-m-d',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^[A-Z]\d[A-Z] ?\d[A-Z]\d$',
        'portals' => ['realtor_com'],
    ],
    'US' => [
        'name' => 'United States',
        'currency' => 'USD',
        'currency_symbol' => '$',
        'locale' => 'en_US',
        'language' => 'en',
        'timezone' => 'America/New_York',
        'date_format' => 'm/d/Y',
        'measurement_system' => 'imperial',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^\d{5}(?:-\d{4})?$',
        'portals' => ['zillow', 'realtor_com'],
    ],
    'ZA' => [
        'name' => 'South Africa',
        'currency' => 'ZAR',
        'currency_symbol' => 'R',
        'locale' => 'en_ZA',
        'language' => 'en',
        'timezone' => 'Africa/Johannesburg',
        'date_format' => 'Y/m/d',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'portals' => [],
    ],
    'NZ' => [
        'name' => 'New Zealand',
        'currency' => 'NZD',
        'currency_symbol' => '$',
        'locale' => 'en_NZ',
        'language' => 'en',
        'timezone' => 'Pacific/Auckland',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'portals' => ['trademe'],
    ],
];
