<?php

return [
    'GB' => [
        'name' => 'United Kingdom',
        'currency' => 'GBP',
        'currency_symbol' => '£',
        'locale' => 'en_GB',
        'language' => 'en',
        'timezone' => 'Europe/London',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$',
        'phone_format' => '+44 #### ######',
        'address_format' => ['line_1', 'line_2', 'city', 'region', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'stamp_duty_land_tax', 'vat_rate' => 20],
        'legal_terms' => ['seller' => 'vendor', 'lawyer' => 'solicitor', 'rental' => 'letting'],
        'portals' => ['rightmove', 'zoopla', 'onthemarket'],
    ],
    'IE' => [
        'name' => 'Ireland',
        'currency' => 'EUR',
        'currency_symbol' => '€',
        'locale' => 'en_IE',
        'language' => 'en',
        'timezone' => 'Europe/Dublin',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^[A-Z0-9]{3} ?[A-Z0-9]{4}$',
        'phone_format' => '+353 ## #######',
        'address_format' => ['line_1', 'line_2', 'town', 'county', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'stamp_duty', 'vat_rate' => 23],
        'legal_terms' => ['seller' => 'vendor', 'lawyer' => 'solicitor', 'rental' => 'letting'],
        'portals' => [],
    ],
    'AU' => [
        'name' => 'Australia',
        'currency' => 'AUD',
        'currency_symbol' => '$',
        'locale' => 'en_AU',
        'language' => 'en',
        'timezone' => 'Australia/Sydney',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'phone_format' => '+61 # #### ####',
        'address_format' => ['line_1', 'line_2', 'suburb', 'state', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'stamp_duty', 'gst_rate' => 10],
        'legal_terms' => ['seller' => 'vendor', 'lawyer' => 'conveyancer', 'rental' => 'rental'],
        'portals' => ['domain', 'realestate_com_au'],
    ],
    'CA' => [
        'name' => 'Canada',
        'currency' => 'CAD',
        'currency_symbol' => '$',
        'locale' => 'en_CA',
        'language' => 'en',
        'timezone' => 'America/Toronto',
        'date_format' => 'Y-m-d',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^[A-Z]\d[A-Z] ?\d[A-Z]\d$',
        'phone_format' => '+1 (###) ###-####',
        'address_format' => ['line_1', 'line_2', 'city', 'province', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'land_transfer_tax', 'gst_rate' => 5],
        'legal_terms' => ['seller' => 'seller', 'lawyer' => 'lawyer', 'rental' => 'rental'],
        'portals' => ['realtor_com'],
    ],
    'US' => [
        'name' => 'United States',
        'currency' => 'USD',
        'currency_symbol' => '$',
        'locale' => 'en_US',
        'language' => 'en',
        'timezone' => 'America/New_York',
        'date_format' => 'm/d/Y',
        'measurement_system' => 'imperial',
        'area_unit' => 'sq_ft',
        'postal_code_pattern' => '^\d{5}(?:-\d{4})?$',
        'phone_format' => '+1 (###) ###-####',
        'address_format' => ['line_1', 'line_2', 'city', 'state', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'state_transfer_tax', 'property_tax' => 'local'],
        'legal_terms' => ['seller' => 'seller', 'lawyer' => 'attorney', 'rental' => 'rental'],
        'portals' => ['zillow', 'realtor_com'],
    ],
    'ZA' => [
        'name' => 'South Africa',
        'currency' => 'ZAR',
        'currency_symbol' => 'R',
        'locale' => 'en_ZA',
        'language' => 'en',
        'timezone' => 'Africa/Johannesburg',
        'date_format' => 'Y/m/d',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'phone_format' => '+27 ## ### ####',
        'address_format' => ['line_1', 'line_2', 'suburb', 'city', 'province', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'transfer_duty', 'vat_rate' => 15],
        'legal_terms' => ['seller' => 'seller', 'lawyer' => 'conveyancer', 'rental' => 'rental'],
        'portals' => [],
    ],
    'NZ' => [
        'name' => 'New Zealand',
        'currency' => 'NZD',
        'currency_symbol' => '$',
        'locale' => 'en_NZ',
        'language' => 'en',
        'timezone' => 'Pacific/Auckland',
        'date_format' => 'd/m/Y',
        'measurement_system' => 'metric',
        'area_unit' => 'sq_m',
        'postal_code_pattern' => '^\d{4}$',
        'phone_format' => '+64 ## ### ####',
        'address_format' => ['line_1', 'line_2', 'suburb', 'city', 'postal_code'],
        'tax_defaults' => ['property_transfer_tax' => 'none', 'gst_rate' => 15],
        'legal_terms' => ['seller' => 'vendor', 'lawyer' => 'conveyancer', 'rental' => 'rental'],
        'portals' => ['trademe'],
    ],
];
